source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'YawImageViewer_Example', :exclusive => true do
  pod "YawImageViewer"
end

target 'YawImageViewer_Tests', :exclusive => true do
  pod "YawImageViewer"

  
end
